In [37]:
import numpy as np
import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split

In [3]:
aStocksTrain = pd.read_csv('acolstocksTrain.csv')
mStocksTest = pd.read_csv('mcolstocksTest.csv')

In [9]:
aStocksTrain.head(5)

,Date,A,AA,AAAP,AAC,AADR,AAL,AAMC,AAME,AAN,...,AYI,AYR,AYT,AYX,AZN,AZO,AZPN,AZRE,AZRX,AZZ
0,2014-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-01-03,1.218414,0.123848,NaN,NaN,0.184038,4.458617,0.544710,2.259984,0.039267,...,0.191663,-0.619026,-0.006476,NaN,0.602720,0.263140,-0.161966,NaN,NaN,-0.639726
3,2014-01-06,0.063120,0.260523,NaN,NaN,-0.565814,2.394917,0.360864,-1.046592,0.309195,...,-1.294586,0.019111,0.033307,NaN,0.352939,0.871230,0.598506,NaN,NaN,-1.087931
4,2014-01-07,0.487010,-0.605852,NaN,NaN,0.400905,-1.536030,1.341908,0.231343,-2.097688,...,1.912880,-1.275911,-0.102969,NaN,-1.362524,0.333081,0.299191,NaN,NaN,-0.502222

In [32]:
# Removing observations with NAN values
aStocksTrain.dropna(axis=0,how='all')

,Date,A,AA,AAAP,AAC,AADR,AAL,AAMC,AAME,AAN,...,AYI,AYR,AYT,AYX,AZN,AZO,AZPN,AZRE,AZRX,AZZ
0,2014-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-01-03,1.218414,0.123848,NaN,NaN,0.184038,4.458617,0.544710,2.259984,0.039267,...,0.191663,-0.619026,-0.006476,NaN,0.602720,0.263140,-0.161966,NaN,NaN,-0.639726
3,2014-01-06,0.063120,0.260523,NaN,NaN,-0.565814,2.394917,0.360864,-1.046592,0.309195,...,-1.294586,0.019111,0.033307,NaN,0.352939,0.871230,0.598506,NaN,NaN,-1.087931
4,2014-01-07,0.487010,-0.605852,NaN,NaN,0.400905,-1.536030,1.341908,0.231343,-2.097688,...,1.912880,-1.275911,-0.102969,NaN,-1.362524,0.333081,0.299191,NaN,NaN,-0.502222
5,2014-01-08,1.579876,2.842494,NaN,NaN,0.368383,2.545666,0.293902,-0.779494,1.384700,...,0.369056,-0.170669,-0.020430,NaN,-0.066544,0.980968,0.257490,NaN,NaN,-15.052740
6,2014-01-09,-0.050620,-0.982805,NaN,NaN,-0.310531,6.147676,6.202170,0.450384,-2.107171,...,11.342857,-0.137899,-0.028597,NaN,1.282456,0.487091,-1.499936,NaN,NaN,-0.143271
7,2014-01-10,0.371322,-5.400032,NaN,NaN,0.056085,-0.835330,3.665324,-0.301763,-0.024919,...,6.538816,1.558437,-0.073221,NaN,1.337672,-0.987103,-0.653868,NaN,NaN,-0.412728
8,2014-01-13,1.682192,1.753100,NaN,NaN,-0.552526,-0.551583,5.982031,0.703932,-5.624825,...,-0.818026,1.316912,0.143698,NaN,-0.201940,0.171774,0.770962,NaN,NaN,1.166337
9,2014-01-14,0.116392,0.907342,NaN,NaN,0.635740,-0.957389,7.346452,-0.029158,-2.079091,...,-1.233260,0.048486,0.731265,NaN,3.008897,0.883273,0.886911,NaN,NaN,-1.060621
10,2014-01-15,0.159028,1.550831,NaN,NaN,-0.326929,-0.851287,3.392393,-0.707611,-1.012257,...,1.775204,-0.968547,-0.057144,NaN,0.956995,-0.495952,0.151120,NaN,NaN,0.881154
11,2014-01-16,0.213653,4.860357,NaN,NaN,0.201630,1.643024,-0.454294,0.423446,-0.269472,...,-0.127837,-0.046532,0.171069,NaN,0.792570,-0.157639,-0.211333,NaN,NaN,0.395237
12,2014-01-17,0.859701,3.407267,NaN,NaN,-0.183091,2.824770,1.051563,-0.516134,1.328374,...,-0.799156,0.060787,0.036398,NaN,0.612122,2.302905,0.041458,NaN,NaN,3.667147
13,2014-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2014-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2014-01-22,-0.013077,0.198700,NaN,NaN,0.295568,1.525926,-2.075097,-0.710929,0.734123,...,0.106872,-0.583099,-0.013141,NaN,0.665399,0.157680,0.607512,NaN,NaN,-0.707283
16,2014-01-23,-1.453012,0.463283,NaN,NaN,-0.832302,1.561201,-5.009695,-0.079132,0.974489,...,-0.303690,-0.249043,0.064293,NaN,1.206408,-0.428434,0.311999,NaN,NaN,1.077872
17,2014-01-24,0.082903,-2.226404,NaN,NaN,-1.397014,0.061875,3.616473,-0.072777,1.822243,...,-1.806216,0.636202,0.244537,NaN,-0.482659,1.541750,-0.448482,NaN,NaN,0.896427
18,2014-01-27,1.745493,2.781973,NaN,NaN,-0.383462,0.339125,-0.424680,-0.321778,1.453636,...,1.538398,1.461931,0.074388,NaN,-0.219551,1.311260,-0.982186,NaN,NaN,2.936071
19,2014-01-28,-1.235692,0.735183,NaN,NaN,-0.191465,4.666127,1.004787,0.258718,-2.118609,...,0.625013,0.317807,-0.946566,NaN,0.041589,-1.099169,1.088830,NaN,NaN,-0.382553
20,2014-01-29,0.653062,2.748510,NaN,NaN,-0.222123,4.707743,-1.804172,-0.807580,1.182117,...,1.236960,0.723094,0.320374,NaN,0.000878,-0.895446,-0.390918,NaN,NaN,-1.273894
21,2014-01-30,1.587804,-1.723714,NaN,NaN,0.474619,0.617070,-0.475953,0.734203,-1.642091,...,-1.912031,-0.661338,-0.165695,NaN,-0.316631,0.129298,1.200341,NaN,NaN,-0.905824
22,2014-01-31,-1.546998,-2.299735,NaN,NaN,0.826493,0.096039,2.310264,-0.839626,1.422143,...,0.614687,0.640552,0.043422,NaN,-0.479504,-0.529587,9.838339,NaN,NaN,0.842377
23,2014-02-03,-0.263232,1.291739,NaN,NaN,-0.590025,4.829392,-0.916671,-1.132408,2.428340,...,0.999305,0.204425,0.275532,NaN,0.968440,-0.726821,0.442608,NaN,NaN,1.429007
24,2014-02-04,1.982433,1.051452,NaN,NaN,0.935087,-0.844476,-1.367128,0.483376,0.118598,...,0.798328,0.764268,-0.102588,NaN,-0.353895,-0.028542,-0.982626,NaN,NaN,-0.188497
25,2014-02-05,-0.245505,-2.825886,NaN,NaN,-0.939924,-0.331947,2.105792,0.438652,0.897617,...,0.360004,-0.732033,-0.027229,NaN,0.990221,0.315120,0.486024,NaN,NaN,0.577656
26,2014-02-06,0.119964,-1.465177,NaN,NaN,1.138040,0.888018,-5.194635,-0.278812,-0.611567,...,-0.534895,0.765624,1.513151,NaN,-2.503368,5.002886,0.171591,NaN,NaN,-0.584661
27,2014-02-07,0.198635,0.267960,NaN,NaN,-0.782883,0.884603,4.630180,-0.856991,3.568391,...,-0.172641,-0.132139,-1.043396,NaN,0.254392,1.968694,-0.225234,NaN,NaN,0.928215
28,2014-02-10,-0.959407,-0.945983,NaN,NaN,0.753056,-0.587469,3.104129,0.450044,3.089657,...,-1.451324,-1.524965,-0.362394,NaN,0.680148,-1.837866,-0.518898,NaN,NaN,0.640701
29,2014-02-11,-0.032306,0.818097,NaN,NaN,0.215159,-2.755845,-0.116369,-0.248232,1.981452,...,-0.729658,-5.260438,-0.124246,NaN,0.737116,1.018773,-0.217405,NaN,NaN,-1.324969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,2017-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
819,2017-02-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
820,2017-02-22,0.167738,-0.094521,0.111202,-2.457315,0.205545,-0.777137,-2.359169,4.466844,0.871118,...,-1.929263,-0.654647,-0.221752,NaN,-0.143359,-0.428240,0.486510,-1.427601,-3.590372,0.391138
821,2017-02-23,0.447301,-6.188667,0.347810,0.019864,-0.666840,-0.201935,-2.212867,-0.131928,0.278582,...,1.649031,-1.403956,0.566242,NaN,2.123097,-0.849151,0.962587,-0.454671,-0.860680,-0.914689
822,2017-02-24,0.094365,1.062495,-0.875236,-2.174821,-1.823056,0.011443,-3.400911,-0.181874,1.230647,...,-0.489774,-0.124731,-0.029407,NaN,-1.090759,0.513275,-0.035789,-15.329880,2.250191,2.000214
823,2017-02-27,-0.648812,0.252303,-0.498834,-0.768177,0.062617,-0.377897,-1.307256,5.105487,-0.030929,...,0.600823,-0.266940,-0.047868,NaN,-0.017168,1.123544,-0.038137,15.619098,5.228979,0.866552
824,2017-02-28,-0.082958,0.618160,2.522270,21.433976,-0.361668,0.838054,-0.236728,-4.036140,1.389273,...,-2.702885,2.313795,0.191907,NaN,-0.211043,-0.218205,-0.197850,1.727542,-6.768635,-1.366001
825,2017-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
826,2017-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
827,2017-03-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
828,2017-03-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
829,2017-03-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
830,2017-03-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
831,2017-03-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
832,2017-03-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
833,2017-03-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
834,2017-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
835,2017-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836,2017-03-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837,2017-03-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
838,2017-03-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839,2017-03-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
840,2017-03-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
841,2017-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
842,2017-03-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
843,2017-03-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
844,2017-03-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
845,2017-03-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
846,2017-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
847,2017-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### KNN

In [14]:
# Instatiating the object
knn = KNeighborsClassifier(n_neighbors=2)

In [30]:
aStocksTrain.iloc[4:5,1:]

,A,AA,AAAP,AAC,AADR,AAL,AAMC,AAME,AAN,AAOI,...,AYI,AYR,AYT,AYX,AZN,AZO,AZPN,AZRE,AZRX,AZZ
4,0.48701,-0.605852,NaN,NaN,0.400905,-1.53603,1.341908,0.231343,-2.097688,1.400914,...,1.91288,-1.275911,-0.102969,NaN,-1.362524,0.333081,0.299191,NaN,NaN,-0.502222

In [33]:
# TODO KNN, implement your own. Using the built library the implementation will be too simple

#### Getting a different dataset

In [34]:
# Creating header
colnames = ['Alcohol','Malic acid','Ash','Alcalinity of ash','Magnesium','Total phenols','Flavanoid',\
            'Nonflavanoid phenols','Proanthocyanis','Color Intensity', 'Hue','OD280/OD315','Proline']

In [35]:
# Reading csv and concatenating the header
wineData = pd.read_csv('wine.data.csv', names=colnames, index_col=False)

In [38]:
# Cross-validation 
trainData, testData = train_test_split(wineData, test_size = 0.2)

### K-Means